### ISSUE TITLE
Προταση

### ISSUE THREAD

**Issue by team7ml** [Deffro/random-dose-of-knowledge#1]
Πολύ καλη ιδέα και εφαρμογή. ισως μπορείς να επιλέγεις τα κορυφαία posts του reddit με πάνω απο κάποια likes, γιατι πολυ συχνά βγάζει άκυρα.Επίσης να μπορείς να κάνεις και κάποια αντίδραση στο post.Πολυ καλή ιδέα παντως

**Comment by Deffro** [comment]
I am translating the text for future readers.

Title: "Suggestion"

Body: "Very nice idea and application. maybe you could only show the top Reddit posts with likes over a chosen threshold because sometimes unrelated posts appear. You could also create a feature so that the user could interact with the post. Very good idea anyway"

Thanks for the feedback! I will take that in mind as I build the next version of the app.
